### ISSUE TITLE
PipeWire

### ISSUE THREAD

**Issue by MrSirKingLord** [haliphax/tts#3]
`pactl load-module module-native-protocol-unix socket=/tmp/pulseaudio.socket`
`Failure: No such entity`

I don't have /tmp/pulseaudio.socket, on my system with pipewire it is an empty folder

As per the instructions on [https://docs.pipewire.org/page_module_protocol_native.html](https://docs.pipewire.org/page_module_protocol_native.html) I modified `/usr/share/pipewire/pipewire.conf`  to setup a unix socket which appears at `/run/user/1000/pipewire-0`

Tried setting `default-server = unix:/run/user/1000/pipewire-0` in the dockerfile and re-build etc but I still get the below error:

```
tts-engine-1  | INFO:root:Speak: test (variant: m3 [random])
tts-engine-1  | Connection failure: Connection refused
tts-engine-1  | pa_context_connect() failed: Connection refused
```
I tried doing `chmod 777 /run/user/1000 -R` but still doesn't work, not sure what to do next

**Comment by haliphax** [comment]
So... if you ran the docker stack _before_ creating that socket, docker is going to try and mount it even if it doesn't exist. In this scenario, it (docker) winds up creating a folder rather than a file. Remove the `/tmp/pulseaudio.socket` folder from your system and be sure that you run the `pactl load-module` command _first_, then bring up the container.

See https://github.com/haliphax/tts/blob/master/run.sh

**Comment by haliphax** [comment]
I realized I have local changes that were never pushed that are necessary for the PipeWire integration. I've updated the repo... you shouldn't need to do any preparation to start the engine now; just fire up the containers. (You will need to rebuild them, however.)

https://github.com/haliphax/tts/commit/ad3db0d1fdf57e4b0cb914a9d19ef6e027bd3555
